repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.3
    hooks:
      - id: clang-format
        files: \.(cpp|hpp|c|h)
  - repo: local
    hooks:
      - id: cppcheck
        name: cppcheck
        entry: make check
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
  - repo: local
    hooks:
      - id: fuzz
        name: fuzz
        entry: make fuzz
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: unit-test
        name: unit-test
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
