name: clang-format
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install clang-format
      run: sudo apt-get install -y clang-format-20
    - name: clang-format
      run: make lint
